services:
  webformhtr.domain:
    image: webformhtr.domain
    build:
      context: .
      dockerfile: WebFormHTR.Domain/Dockerfile

  webformhtr.api:
    image: webformhtr.api
    build:
      context: .
      dockerfile: WebFormHTR.API/Dockerfile
