// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebFormHTR.Infrastructure.Persistence;

#nullable disable

namespace WebFormHTR.Infrastructure.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251129172324_MakeTemplateFileRequired")]
    partial class MakeTemplateFileRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("WebFormHTR.Domain.Entities.ExtractedValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectedValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LogsheetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoiId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogsheetId");

                    b.ToTable("ExtractedValues");
                });

            modelBuilder.Entity("WebFormHTR.Domain.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("WebFormHTR.Domain.Entities.Logsheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlignmentData")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("Logsheets");
                });

            modelBuilder.Entity("WebFormHTR.Domain.Entities.Residual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Residuals");
                });

            modelBuilder.Entity("WebFormHTR.Domain.Entities.Roi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExtractedValueId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExtractedValueId")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("Rois");
                });

            modelBuilder.Entity("WebFormHTR.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("WebFormHTR.Domain.Entities.ExtractedValue", b =>
                {
                    b.HasOne("WebFormHTR.Domain.Entities.Logsheet", "Logsheet")
                        .WithMany("ExtractedValues")
                        .HasForeignKey("LogsheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logsheet");
                });

            modelBuilder.Entity("WebFormHTR.Domain.Entities.Logsheet", b =>
                {
                    b.HasOne("WebFormHTR.Domain.Entities.File", "File")
                        .WithOne()
                        .HasForeignKey("WebFormHTR.Domain.Entities.Logsheet", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebFormHTR.Domain.Entities.Template", "Template")
                        .WithMany("Logsheets")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("WebFormHTR.Domain.Entities.Residual", b =>
                {
                    b.HasOne("WebFormHTR.Domain.Entities.Template", "Template")
                        .WithMany("Residuals")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WebFormHTR.Domain.ValueObjects.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<Guid>("ResidualId")
                                .HasColumnType("TEXT");

                            b1.Property<float>("Height")
                                .HasColumnType("REAL");

                            b1.Property<float>("Width")
                                .HasColumnType("REAL");

                            b1.Property<float>("X")
                                .HasColumnType("REAL");

                            b1.Property<float>("Y")
                                .HasColumnType("REAL");

                            b1.HasKey("ResidualId");

                            b1.ToTable("Residuals");

                            b1.WithOwner()
                                .HasForeignKey("ResidualId");
                        });

                    b.Navigation("Coordinates")
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("WebFormHTR.Domain.Entities.Roi", b =>
                {
                    b.HasOne("WebFormHTR.Domain.Entities.ExtractedValue", "ExtractedValue")
                        .WithOne("Roi")
                        .HasForeignKey("WebFormHTR.Domain.Entities.Roi", "ExtractedValueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebFormHTR.Domain.Entities.Template", "Template")
                        .WithMany("Rois")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WebFormHTR.Domain.ValueObjects.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<Guid>("RoiId")
                                .HasColumnType("TEXT");

                            b1.Property<float>("Height")
                                .HasColumnType("REAL");

                            b1.Property<float>("Width")
                                .HasColumnType("REAL");

                            b1.Property<float>("X")
                                .HasColumnType("REAL");

                            b1.Property<float>("Y")
                                .HasColumnType("REAL");

                            b1.HasKey("RoiId");

                            b1.ToTable("Rois");

                            b1.WithOwner()
                                .HasForeignKey("RoiId");
                        });

                    b.Navigation("Coordinates")
                        .IsRequired();

                    b.Navigation("ExtractedValue");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("WebFormHTR.Domain.Entities.Template", b =>
                {
                    b.HasOne("WebFormHTR.Domain.Entities.File", "File")
                        .WithOne()
                        .HasForeignKey("WebFormHTR.Domain.Entities.Template", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebFormHTR.Domain.Entities.Template", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("File");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("WebFormHTR.Domain.Entities.ExtractedValue", b =>
                {
                    b.Navigation("Roi")
                        .IsRequired();
                });

            modelBuilder.Entity("WebFormHTR.Domain.Entities.Logsheet", b =>
                {
                    b.Navigation("ExtractedValues");
                });

            modelBuilder.Entity("WebFormHTR.Domain.Entities.Template", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Logsheets");

                    b.Navigation("Residuals");

                    b.Navigation("Rois");
                });
#pragma warning restore 612, 618
        }
    }
}
