// <auto-generated />
using System;
using LogsheetXtractor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogsheetXtractor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("LogsheetXtractor.Domain.Entities.ExtractedValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectedValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LogsheetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoiId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationRulesVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationWarnings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogsheetId");

                    b.HasIndex("RoiId");

                    b.ToTable("ExtractedValues");
                });

            modelBuilder.Entity("LogsheetXtractor.Domain.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("LogsheetXtractor.Domain.Entities.Logsheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlignmentData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("Logsheets");
                });

            modelBuilder.Entity("LogsheetXtractor.Domain.Entities.PredefinedRoiValidationCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoiType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code", "RoiType")
                        .IsUnique();

                    b.ToTable("PredefinedRoiValidationConditions");
                });

            modelBuilder.Entity("LogsheetXtractor.Domain.Entities.Residual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("Residuals");
                });

            modelBuilder.Entity("LogsheetXtractor.Domain.Entities.Roi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationCondition")
                        .HasColumnType("TEXT");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "VariableName")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("Rois");
                });

            modelBuilder.Entity("LogsheetXtractor.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BacksideTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BacksideTemplateId")
                        .IsUnique();

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("ParentId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("LogsheetXtractor.Infrastructure.Persistence.Entities.UserCredentialHandle", b =>
                {
                    b.Property<string>("Handle")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Handle");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("UserCredentialHandles");
                });

            modelBuilder.Entity("LogsheetXtractor.Domain.Entities.ExtractedValue", b =>
                {
                    b.HasOne("LogsheetXtractor.Domain.Entities.Logsheet", "Logsheet")
                        .WithMany("ExtractedValues")
                        .HasForeignKey("LogsheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogsheetXtractor.Domain.Entities.Roi", "Roi")
                        .WithMany()
                        .HasForeignKey("RoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logsheet");

                    b.Navigation("Roi");
                });

            modelBuilder.Entity("LogsheetXtractor.Domain.Entities.Logsheet", b =>
                {
                    b.HasOne("LogsheetXtractor.Domain.Entities.File", "File")
                        .WithOne()
                        .HasForeignKey("LogsheetXtractor.Domain.Entities.Logsheet", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogsheetXtractor.Domain.Entities.Template", "Template")
                        .WithMany("Logsheets")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("LogsheetXtractor.Domain.Entities.Residual", b =>
                {
                    b.HasOne("LogsheetXtractor.Domain.Entities.Template", "Template")
                        .WithMany("Residuals")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LogsheetXtractor.Domain.ValueObjects.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<Guid>("ResidualId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Height")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Width")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("X")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Y")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ResidualId");

                            b1.ToTable("Residuals");

                            b1.WithOwner()
                                .HasForeignKey("ResidualId");
                        });

                    b.Navigation("Coordinates")
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("LogsheetXtractor.Domain.Entities.Roi", b =>
                {
                    b.HasOne("LogsheetXtractor.Domain.Entities.Template", "Template")
                        .WithMany("Rois")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LogsheetXtractor.Domain.ValueObjects.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<Guid>("RoiId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Height")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Width")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("X")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Y")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RoiId");

                            b1.ToTable("Rois");

                            b1.WithOwner()
                                .HasForeignKey("RoiId");
                        });

                    b.Navigation("Coordinates")
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("LogsheetXtractor.Domain.Entities.Template", b =>
                {
                    b.HasOne("LogsheetXtractor.Domain.Entities.Template", "BacksideTemplate")
                        .WithOne("FrontsideTemplate")
                        .HasForeignKey("LogsheetXtractor.Domain.Entities.Template", "BacksideTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogsheetXtractor.Domain.Entities.File", "File")
                        .WithOne()
                        .HasForeignKey("LogsheetXtractor.Domain.Entities.Template", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogsheetXtractor.Domain.Entities.Template", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BacksideTemplate");

                    b.Navigation("File");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("LogsheetXtractor.Domain.Entities.Logsheet", b =>
                {
                    b.Navigation("ExtractedValues");
                });

            modelBuilder.Entity("LogsheetXtractor.Domain.Entities.Template", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("FrontsideTemplate");

                    b.Navigation("Logsheets");

                    b.Navigation("Residuals");

                    b.Navigation("Rois");
                });
#pragma warning restore 612, 618
        }
    }
}
